const SUPABASE_URL='https://nnflqxkexcmncendyaas.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_soMUpvwfZ4jwkG2sT6RbZg_RDoRzMXd';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])), toast=m=>{const e=$('#toast');if(e){e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}};
let user=null,channel=null;
function openAuth(){if($('#authModal')){$('#authModal').hidden=false;return}document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="authModal"><div class="auth-modal"><button class="modal-close" id="closeAuth">×</button><p class="eyebrow">Bahia em Dia</p><h2 id="authTitle">Entrar na torcida</h2><form id="authForm"><input id="authName" placeholder="Seu nome" hidden><input id="authEmail" type="email" placeholder="Seu e-mail" required><input id="authPassword" type="password" placeholder="Senha (mínimo 6 caracteres)" minlength="6" required><button class="button primary" id="authSubmit">Entrar</button></form><button class="auth-switch" id="authSwitch">Ainda não tenho conta</button><p id="authError" class="auth-error"></p></div></div>`);let signup=false;const render=()=>{$('#authTitle').textContent=signup?'Criar conta':'Entrar na torcida';$('#authSubmit').textContent=signup?'Criar conta':'Entrar';$('#authName').hidden=!signup;$('#authName').required=signup;$('#authSwitch').textContent=signup?'Já tenho uma conta':'Ainda não tenho conta'};$('#closeAuth').onclick=()=>$('#authModal').remove();$('#authSwitch').onclick=()=>{signup=!signup;render()};$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='Aguarde...';const email=$('#authEmail').value.trim(),password=$('#authPassword').value;const r=signup?await db.auth.signUp({email,password,options:{data:{display_name:$('#authName').value.trim()}}}):await db.auth.signInWithPassword({email,password});if(r.error)$('#authError').textContent=r.error.message;else{closeAuth();toast(signup?'Conta criada. Verifique seu e-mail.':'Login realizado.');await refresh()}};render()}
async function refresh(){const r=await db.auth.getUser();user=r.data.user;const b=$('#accountBtn');if(b)b.textContent=user?'Sair':'Entrar';if($('#chatStatus'))$('#chatStatus').textContent=user?'Acesso gratuito · 3 mensagens por dia':'Entre para participar';if(user)loadChat();else if($('#messages'))$('#messages').innerHTML='<p class="empty-state">Entre para participar da resenha.</p>'}
async function account(){if(user){await db.auth.signOut();toast('Você saiu da conta.');await refresh()}else openAuth()}
async function news(){const g=$('#newsGrid');if(!g)return;g.innerHTML='<p class="loading">Carregando notícias...</p>';const r=await db.from('news').select('title,summary,image_url,published_at,slug,news_categories(name)').eq('status','published').order('published_at',{ascending:false}).limit(12);if(r.error||!r.data?.length){g.innerHTML='<p class="empty-state">Ainda não há notícias publicadas.</p>';return}g.innerHTML=r.data.map(n=>`<article class="news-card"><div class="news-art" style="background-image:${n.image_url?\`url("${esc(n.image_url)}")\`:'linear-gradient(135deg,#003b7a,#0756a0)'}"><span>${esc(n.news_categories?.name||'Bahia')}</span></div><div class="news-body"><small>${n.published_at?new Date(n.published_at).toLocaleDateString('pt-BR'):'Hoje'}</small><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p></div></article>`).join('')}
function message(m){return`<div class="message"><b>${esc(m.profiles?.display_name||'Torcedor')}</b><p>${esc(m.content)}</p><small>${new Date(m.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div>`}
async function loadChat(){const box=$('#messages');if(!box||!user)return;const r=await db.from('chat_messages').select('id,content,created_at,profiles(display_name)').order('created_at',{ascending:true}).limit(100);box.innerHTML=r.error?'<p class="empty-state">Não foi possível carregar o chat.</p>':r.data?.length?r.data.map(message).join(''):'<p class="empty-state">A resenha começa com você.</p>';box.scrollTop=box.scrollHeight;if(channel)db.removeChannel(channel);channel=db.channel('bahia-chat').on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_messages'},()=>loadChat()).subscribe()}
async function send(e){e.preventDefault();if(!user){openAuth();return}const i=$('#chatInput'),v=i.value.trim();if(!v)return;const r=await db.rpc('post_chat_message',{message_content:v});if(r.error){toast(r.error.message.includes('DAILY_LIMIT')?'Limite gratuito diário atingido.':'Não foi possível enviar.');return}i.value='';await loadChat()}
async function stream(){const r=await db.from('streams').select('*').order('starts_at',{ascending:false}).limit(1).maybeSingle(),p=$('#streamPill'),v=$('#video'),ph=document.querySelector('.player-placeholder');if(r.error||!r.data||!r.data.is_open){if(p){p.textContent='● Fechada';p.className='status-pill closed'}if(ph)ph.innerHTML='<span class="play-icon">▶</span><h3>A transmissão não está disponível neste momento.</h3>';if(v){v.hidden=true;v.removeAttribute('src')}return}const s=r.data;if(p){p.textContent='● Aberta';p.className='status-pill open'}if(ph)ph.hidden=true;if(v){v.hidden=false;v.src=s.media_url}if($('#playerTitle'))$('#playerTitle').textContent=s.title}
document.addEventListener('DOMContentLoaded',async()=>{const script=document.createElement('script');if(!window.supabase){script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4';script.onload=()=>location.reload();document.head.appendChild(script);return}if($('#accountBtn'))$('#accountBtn').onclick=account;if($('#chatForm'))$('#chatForm').onsubmit=send;$('#demoToggle')?.remove();await news();await stream();await refresh();db.auth.onAuthStateChange(()=>refresh())});